version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Build completed"
  post_build:
    commands:
      - echo "Post build completed"

artifacts:
  files:
    - '**/*'
